apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  namespace: backstage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-service-account-binding
subjects:
  - kind: ServiceAccount
    name: my-service-account
    namespace: backstage
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
