apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: stack-addons
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/gopaljayanthi/forjpmc.git
        revision: HEAD
        files:
        - path: "stack/kube-prometheus-stack/dev/config.json"
  syncPolicy:
    preserveResourcesOnDeletion: true
  strategy:
    type: AllAtOnce
  template:
    metadata:
      name: in-cluster-{{name}}
    spec:
      project: default
      sources:
        - repoURL: '{{repoURL}}'
          targetRevision: '{{targetRevision}}'
          chart: '{{chart}}'
          helm:
            releaseName: '{{name}}'
      destination:
        name: in-cluster
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          #- PrunePropagationPolicy=orphan
        retry:
          limit: 10
          backoff:
            duration: 60s
            factor: 2
            maxDuration: 2m