apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myplugin
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - plugin:
        configMapRef:
          name: applicationset-hello-plugin
        input:
          parameters:
            repo: "gopaljayanthi/forjpmc"
            branch: "master"
            folder: "pluginfiles"
        requeueAfterSeconds: 60
  template:
    metadata:
      name: "myplugin"
      annotations:
        example.from.plugin.output: "{{ .contents }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/gopaljayanthi/forjpmc.git
        path: test-plugin-helm
        targetRevision: master
      destination:
        server: https://kubernetes.default.svc
        namespace: default
  templatePatch: |
    spec:
      source:
        helm:
          parameters:
          {{- if .contents }}
          {{- range $fileName, $fileContents := .contents }}
            - name: 'configMapFiles.{{ $fileName | replace "." "\\." }}'
              value: '{{ $fileContents }}'
          {{- end }}
            - name: "name"
              value: '{{.name}}'
          {{- end }}