apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  annotations:
    artifact.spinnaker.io/location: spin-argo-trigger
    artifact.spinnaker.io/name: nginx-deployment
    artifact.spinnaker.io/type: kubernetes/deployment
    moniker.spinnaker.io/application: spinargoapp
    moniker.spinnaker.io/cluster: deployment nginx-deployment
  labels:
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: spinargoapp
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      annotations:
        artifact.spinnaker.io/location: spin-argo-trigger
        artifact.spinnaker.io/name: nginx-deployment
        artifact.spinnaker.io/type: kubernetes/deployment
        moniker.spinnaker.io/application: spinargoapp
        moniker.spinnaker.io/cluster: deployment nginx-deployment
      labels:
        app: nginx
        app.kubernetes.io/managed-by: spinnaker
        app.kubernetes.io/name: spinargoapp
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.6
        ports:
        - containerPort: 80
