apiVersion: batch/v1
kind: Job
metadata:
  name: sleep-job
spec:
  template:
    spec:
      containers:
      - name: sleep-container
        image: busybox
        command: ["sleep", "6"]
      restartPolicy: Never
  backoffLimit: 2
