kind: Service
apiVersion: v1
metadata:
  name: nginx
  annotations:
    artifact.spinnaker.io/location: tcbargo
    artifact.spinnaker.io/name: nginx
    artifact.spinnaker.io/type: kubernetes/service
    moniker.spinnaker.io/application: spinargoapp
    moniker.spinnaker.io/cluster: service nginx
  labels:
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: spinargoapp
spec:
  selector:
    app: "nginx"
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-2
  annotations:
    artifact.spinnaker.io/location: tcbargo
    artifact.spinnaker.io/name: nginx-2
    artifact.spinnaker.io/type: kubernetes/service
    moniker.spinnaker.io/application: spinargoapp
    moniker.spinnaker.io/cluster: service nginx-2
  labels:
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: spinargoapp
spec:
  selector:
    app: "nginx"
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: ClusterIP
