apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
data:
  {{- if .Values.configMapFiles }}
  {{- range $fileName, $fileContents := .Values.configMapFiles }}
  {{ $fileName }}: |-
    {{- $fileContents | nindent 4 }}
  {{- end }}
  {{- end }}
