apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: matrix-multicm-myplugin
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/gopaljayanthi/forjpmc.git
              revision: HEAD
              files:
                - path: "test-git-files-generator/dev/config.json"
          - plugin:
              configMapRef:
                name: applicationset-hello-plugin
              input:
                parameters:
                  repo: "gopaljayanthi/forjpmc"
                  branch: "master"
                  folder: "pluginfiles"
            #requeueAfterSeconds: 120
  template:
    metadata:
      name: "multicm-myplugin"
      annotations:
        example.from.plugin.output: '{{ .label }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/gopaljayanthi/forjpmc.git
        path: multicm-plugin-helm
        targetRevision: master
      destination:
        server: https://kubernetes.default.svc
        namespace: default
  templatePatch: |
    spec:
      source:
        helm:
          parameters:
          {{- if .contents }}
          {{- range $fileName, $fileContents := .contents }}
            - name: 'configMapFiles.{{ $fileName | replace "." "\\." }}'
              value: '{{ $fileContents }}'
          {{- end }}
            - name: "name"
              value: '{{.name}}'
          {{- end }}